[package]
name = "tekhne"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.13", features = ["derive"] }
glam = { version = "0.24", features = ["bytemuck"] }
pollster = "0.3"
wgpu = "0.16"
winit = { version = "0.28", default-features = false, features = ["x11", "wayland"] }
