[package]
name = "tekhne"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.23"

[dependencies.bevy]
version = "0.10"
default-features = false
features = [
 "bevy_asset",
 "bevy_sprite",
 "bevy_core_pipeline",
 "bevy_render",
 "wayland",
]
