[package]
name = "tekhne"
version = "0.1.0"
edition = "2021"

[dependencies]
aabb = { path = "crates/aabb" }
ahash = "0.8"
bytemuck = { version = "1.14", features = ["derive"] }
glam = { version = "0.24", features = ["bytemuck"] }
image = "0.24"
image-atlas = "0.2"
pollster = "0.3"
rand = "0.8"
rectangle-pack = "0.4"
slab = "0.4"
wgpu = "0.17"
winit = "0.28"
winit_input_helper = "0.14"

[workspace]
members = ["crates/*"]
