[package]
name = "tekhne"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.24"
pollster = "0.3"
wgpu = "0.16"
winit = { version = "0.28", default-features = false, features = ["x11", "wayland"] }
