[package]
name = "aabb"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = []

[dependencies.glam]
version = "0.24"
default-features = false

[dependencies.float_next_after]
version = "1"
default-features = false
